services:
  - type: web
    name: design-assistant-backend
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port 8000"
    plan: free

  - type: web
    name: design-assistant-frontend
    env: node
    buildCommand: "cd frontend && npm install && npm run build"
    startCommand: "cd frontend && npm install -g serve && serve -s build -l 3000"
    plan: free
